apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    {{- include "postgresql-cluster.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    team: acid
  {{- with .Values.annotations}}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "postgresql-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  allowedSourceRanges: null
  {{- with .Values.databases }}
  databases:
    {{- toYaml .Values.databases | nindent 4 }}
  {{- end }}
  numberOfInstances: {{ .Values.numberOfInstances }}
  postgresql:
    version: {{ .Values.postgresql.version | toString }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  teamId: acid
  {{- with .Values.users }}
  users:
    {{- toYaml .Values.users | nindent 4 }}
  {{- end }}
  volume:
    size: {{ .Values.volume.size }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
  {{- end }}
  {{- with.Values.nodeAffinity }}
  nodeAffinity:
    {{- toYaml .Values.nodeAffinity | nindent 4 }}
  {{- end }}
  {{- with .Values.initContainers }}
  initContainers:
    {{- toYaml .Values.initContainers | nindent 4 }}
  {{- end }}
  {{- with .Values.sidecars }}
  sidecars:
    {{- toYaml .Values.sidecars | nindent 4 }}
  {{- end }}
